### ISSUE TITLE
Write example for RedPajama

### ISSUE THREAD

**Issue by mitchellnw** [mosaicml/streaming#248]
## 🚀 Feature Request
Write example (like https://github.com/mosaicml/streaming/blob/main/streaming/text/convert/pile.py) for RedPajama

## Motivation

It would be helpful to have a write example like you have for C4 but for RedPajama.

**Comment by mitchellnw** [comment]
Thanks! Was more just wondering if you had it lying around already as I saw you were training some rpj models, don't want to cause any extra work :)

**Comment by mitchellnw** [comment]
Another question about using mosaic streaming -- which seems like a pretty incredible tool.

Do you have any very simple getting started examples that may resemble what I have below, but actually work?

I can't seem to figure out what's wrong with the below... I am doing:

```
from torch.utils.data import DataLoader
from streaming.base import StreamingDataset
import tiktoken
import torch
import os

def chunk_generator(dataset, batch_size, seqlen, enc, sampler=None):
    chunks = []
    indices = iter(sampler) if sampler else range(len(dataset))
    
    for idx in indices:
        sample = dataset[idx]
        doc = torch.Tensor(enc.encode(sample['text'])).to(torch.long)
        num_chunks, remainder = divmod(len(doc), seqlen)

        if remainder:
            padding = torch.zeros(seqlen - remainder, dtype=doc.dtype)
            doc = torch.cat([doc, padding])
            num_chunks += 1

        chunks.extend(doc.view(num_chunks, seqlen))

        while len(chunks) >= batch_size:
            yield torch.stack(chunks[:batch_size])
            chunks = chunks[batch_size:]

class CustomDataLoader(DataLoader):
    def __init__(self, dataset, batch_size, seqlen, enc, *args, **kwargs):
        sampler = None
        super().__init__(dataset, batch_size=batch_size, *args, **kwargs)
        self.generator = chunk_generator(dataset, batch_size, seqlen, enc, sampler)

    def __iter__(self):
        return self.generator


if __name__ == "__main__":
    # Remote path where full dataset is persistently stored
    #remote = '/fsx/home-mitchellw/rpj-proc/arxiv/'
    remote = 's3://<path-to-data>'
    local = '/scratch/tmp/cache'

    enc = tiktoken.get_encoding("p50k_base")

    dataset = StreamingDataset(
        local=local, 
        remote=remote, 
    )

    dataloader = CustomDataLoader(dataset, batch_size=2, seqlen=20, enc=enc, num_workers=0)


    for j, data in enumerate(dataloader):
        print(enc.decode(data[0].tolist()) + '~' + enc.decode(data[1].tolist()))
        print('---')
        if j == 10:
            exit()

```

And I get the error

```
Traceback (most recent call last):
  File "test_dataloader_non_distributed.py", line 45, in <module>
    dataset = StreamingDataset(
  File "~/miniconda3/envs/py2/lib/python3.8/site-packages/streaming/base/dataset.py", line 325, in __init__
    self._shm_prefix, self._locals_shm = get_shm_prefix(my_locals, world)
  File "~/miniconda3/envs/py2/lib/python3.8/site-packages/streaming/base/shared.py", line 340, in get_shm_prefix
    raise ValueError(f'Reused local directory: {sorted(my_locals_set)} vs ' +
ValueError: Reused local directory: ['/scratch/tmp/cache'] vs ['/scratch/tmp/cache']. Provide a different one.
```

If I use `local=None` then it works for a single device but fails in the distributed setting.

I believe this question is similar to https://github.com/mosaicml/streaming/issues/225

**Comment by dakinggg** [comment]
@karan6181 will know for sure, but can you try deleting /scratch/tmp/cache, or changing that path? I think sometimes if streaming crashes it may not properly cleanup the shared memory files.

**Comment by knighton** [comment]
Are you running this on multiple processes? If so, are you setting the required env vars before execution? If env vars aren't set, each StreamingDataset replica in each process will default assume it is alone in this world. They will each try to register `/scratch/tmp/cache` as a local working directory belonging to them, and these registrations will collide, which would cause the above error. Apologies that this isn't properly explained.

If this is the problem, you might try something like
```
RANK=0 WORLD_SIZE=4 LOCAL_WORLD_SIZE=4 python3 main.py
```

**Comment by mitchellnw** [comment]
Thanks! Daniel's suggestion of changing the path worked. Interestingly when I did `rm -rf /scratch/tmp/cache` then re-ran it still broke, but when I used `local = '/scratch/tmp2/cache'` it worked again.

So I guess it was just non-proper clean-up, thanks for the help and sorry to bother!

I'm currently looking into mosiac streaming as a replacement for webdataset which is what I was previously using. While I'm here I have a quick question about the distributed setting...

If I run on, e.g., 8 nodes each with 8 processes each, the StremingDataset will just handle this -- each process will have a mutually exclusive set of shards that it reads?

**Comment by knighton** [comment]
Glad to hear. Ah yes, doing better than WebDataset was our original impetus.

Mapping sub-datasets ("streams"), shards, and samples to nodes, ranks, and workers is non-trivial! At the highest level, yes, we don't do any unnecessary shard downloads. But we are shy of perfect shard efficiency in practice -- StreamingDataset is built for an imperfect world where subsets/shards/samples and nodes/ranks/workers don't evenly divide into each other. While the unit of download is the shard, we actually work in terms of exact samples.

Visualize how we partition the sample space from your browser with this FastAPI app: https://github.com/mosaicml/streaming/blob/main/scripts/partition/web.py

Who gets what samples in what order is laid out at the start of the epoch as a 5d int64 tensor (nodes, ranks, workers, batches, samples), in a design that preserves determinism even if you scale up or down the number of nodes. As each worker iterates and yields from its partition of the sample space, it has a couple threads that iterate ahead, pre-downloading and decompressing the shards of the samples it is about to need. This downloading/evicting is all happening in parallel, with workers sharing load via shared memory.

StreamingDataset currently has four shuffling algorithms, which have different properties. They generally try to intermix samples from different shards in order to counteract different sub-datasets having wildly different data distributions, strong up/down-sampling, a poor or non-existent pre-shuffle, or other weaknesses. This can be tuned up or down by certain arguments to StreamingDataset.

Partitioning and shuffling (with the exception of the `naive` shuffle algo) are also designed to preserve shards on the same node across epochs, so that subsequent epochs are entirely locally cached (assuming your cache limit will handle the entire dataset). For a cached performance comparison, see https://github.com/mosaicml/streaming/blob/main/scripts/serialization/compare.py

**Comment by karan6181** [comment]
Hi @mitchellnw, closing this issue due to inactivity. Please don't hesitate to open the issue.
