### ISSUE TITLE
MDSWriter encountered GCS upload error but kept going

### ISSUE THREAD

**Issue by genesis-jamin** [mosaicml/streaming#459]
Hi, I was writing to Google Cloud Storage with `MDSWriter` and hit an error about exceeding the rate limit. The code printed the exception but still continued executing, so I ended up with a directory where the `index.json` file was present but the shard was not. Is it expected for exceptions during shard upload to be printed but not raised?

Stacktrace:

```
[23/10/03 23:33:21 ERROR _base.py:344] exception calling callback for <Future at 0x7f8d0c1137f0 state=finished raised TooManyRequests>
Traceback (most recent call last):
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2540, in upload_from_file
    created_json = self._do_upload(
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2355, in _do_upload
    response = self._do_multipart_upload(
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 1890, in _do_multipart_upload
    response = upload.transmit(
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
    return _request_helpers.wait_and_retry(
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py", line 171, in wait_and_retry
    raise error
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py", line 148, in wait_and_retry
    response = func()
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 149, in retriable_request
    self._process_response(result)
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/resumable_media/_upload.py", line 114, in _process_response
    _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 429, 'Expected one of', <HTTPStatus.OK: 200>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda/envs/main-env/lib/python3.10/concurrent/futures/_base.py", line 342, in _invoke_callbacks
    callback(self)
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/streaming/base/format/base/writer.py", line 283, in exception_callback
    raise exception
  File "/root/miniconda/envs/main-env/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/streaming/base/storage/upload.py", line 331, in upload_file
    blob.upload_from_filename(local_filename)
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2684, in upload_from_filename
    self.upload_from_file(
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2557, in upload_from_file
    _raise_from_invalid_response(exc)
  File "/root/miniconda/envs/main-env/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 4373, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.TooManyRequests: 429 POST https://storage.googleapis.com/upload/storage/v1/b/genesis-cloud-queue/o?uploadType=multipart: {
  "error": {
    "code": 429,
    "message": "You have exceeded your bucket's IO capacity. Please follow the request rate and access distribution guidelines at https://cloud.google.com/storage/docs/conformance in order to  avoid temporary limits on your bucket.",
    "errors": [
      {
        "message": "You have exceeded your bucket's IO capacity. Please follow the request rate and access distribution guidelines at https://cloud.google.com/storage/docs/conformance in order to  avoid temporary limits on your bucket.",
        "domain": "usageLimits",
        "reason": "rateLimitExceeded"
      }
    ]
  }
}
: ('Request failed with status code', 429, 'Expected one of', <HTTPStatus.OK: 200>)
```

**Comment by karan6181** [comment]
Hi @genesis-jamin, are you using streaming dataset version `0.6.0` or from `main`?

**Comment by genesis-jamin** [comment]
Sorry I should have specified, we're using `0.5.2` -- was this issue fixed since then?

**Comment by karan6181** [comment]
Yes. Can you please try `main`? Please let us know if you still see the issue. The expected behavior is that the `index.json` should not get uploaded when there is a crash, and when there is a crash, it should terminate the job.

**Comment by karan6181** [comment]
Hi @genesis-jamin, did you get to try out streaming `main.` I think the issue that you are seeing is fixed. Please let us know if that's not the case. Thank You!

**Comment by karan6181** [comment]
Closing this issue for now. Please feel free to re-open if the issue persists.
