### ISSUE TITLE
`ValueError: invalid literal for int() with base 10` when instantiating `StreamingDataset`

### ISSUE THREAD

**Issue by genesis-jamin** [mosaicml/streaming#461]
## Environment

- OS: Ubuntu 18.04
- Hardware (GPU, or instance type): Nvidia Tesla T4

## To reproduce

**I installed `mosaicml-streaming` off of the latest commit: https://github.com/mosaicml/streaming/commit/6b638518294f7338f7bb54e9bb529bfad8e5fa50**

I ran the following code bit:

```python
from streaming import MDSWriter, StreamingDataset


path = 'gs://genesis-cloud-queue/datasets/jamin/mosaic_test'

with MDSWriter(out=path, columns={'value': 'int'}) as out:
    for value in range(5):
        out.write({'value': value})


dataset = StreamingDataset(remote=path)
for i in range(dataset.size):
    print(dataset[i])
```

which gave me this error:
```
Traceback (most recent call last):
  File "/home/jamin/deep-affinity/mosaic.py", line 11, in <module>
    dataset = StreamingDataset(remote=path)
  File "/home/jamin/.conda/envs/main-env/lib/python3.10/site-packages/streaming/base/dataset.py", line 496, in __init__
    self._shm_prefix_int, self._locals_shm = get_shm_prefix(streams_local, streams_remote,
  File "/home/jamin/.conda/envs/main-env/lib/python3.10/site-packages/streaming/base/shared/prefix.py", line 189, in get_shm_prefix
    prefix_int = _check_and_find_retrying(streams_local, streams_remote, retry)
  File "/home/jamin/.conda/envs/main-env/lib/python3.10/site-packages/streaming/base/shared/prefix.py", line 162, in _check_and_find_retrying
    raise errs[-1]
  File "/home/jamin/.conda/envs/main-env/lib/python3.10/site-packages/streaming/base/shared/prefix.py", line 158, in _check_and_find_retrying
    return _check_and_find(streams_local, streams_remote)
  File "/home/jamin/.conda/envs/main-env/lib/python3.10/site-packages/streaming/base/shared/prefix.py", line 115, in _check_and_find
    their_locals, _ = _unpack_locals(bytes(shm.buf))
  File "/home/jamin/.conda/envs/main-env/lib/python3.10/site-packages/streaming/base/shared/prefix.py", line 75, in _unpack_locals
    return text[:-1], int(text[-1] or 0)
ValueError: invalid literal for int() with base 10: '/tmp/tmpzsvx0xho'
```

## Expected behavior

We should be able to read the dataset's contents or raise a more informative error.

**Comment by genesis-jamin** [comment]
If it helps, we were not seeing this issue on version `0.5.2.` but have started seeing this after installing the latest commit on `main`.

**Comment by karan6181** [comment]
Interesting! I just now verified on MAC with the above script by passing `path=<local>` and `path=<cloud_url>` and it works for me in both cases. Below is the output I received.

```
{'value': 0}
{'value': 1}
{'value': 2}
{'value': 3}
{'value': 4}
```

**Comment by genesis-jamin** [comment]
Thanks, I did some digging and realized that I had a bunch of child processes that were left hanging on my system. These child processes would have created `StreamingDataset` instances, so I'm guessing that we just hit some type of limit on shared memory. Killing these processes solved my issue.
