### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by murthyrudra** [mosaicml/streaming#591]
## Environment
```
Package                     Version      Editable project location
--------------------------- ------------ --------------------------------------------------
accelerate                  0.26.1
aim                         3.17.2
aim-ui                      3.17.2
aimrecords                  0.0.7
aimrocks                    0.4.0
aiobotocore                 2.7.0
aiofiles                    23.1.0
aiohttp                     3.9.2
aioitertools                0.11.0
aiolimiter                  1.1.0
aiosignal                   1.3.1
alembic                     1.11.1
apex                        0.1
appdirs                     1.4.4
async-timeout               4.0.2
backoff                     2.2.1
base58                      2.0.1
bitsandbytes                0.40.2
black                       23.7.0
boto                        2.49.0
boto3                       1.34.29
botocore                    1.34.30
datasets                    2.16.1
deepspeed                   0.12.0
einops                      0.6.1
evaluate                    0.4.0
faiss-cpu                   1.7.4
mosaicml                    0.14.1
mosaicml-streaming          0.7.3
nvidia-cublas-cu11          11.10.3.66
nvidia-cuda-cupti-cu11      11.7.101
nvidia-cuda-nvrtc-cu11      11.7.99
nvidia-cuda-runtime-cu11    11.7.99
nvidia-cudnn-cu11           8.5.0.96
nvidia-cufft-cu11           10.9.0.58
nvidia-curand-cu11          10.2.10.91
nvidia-cusolver-cu11        11.4.0.1
nvidia-cusparse-cu11        11.7.4.91
nvidia-nccl-cu11            2.14.3
nvidia-nvtx-cu11            11.7.91
omegaconf                   2.2.3
requests                    2.31.0
s3fs                        2023.10.0
s3transfer                  0.10.0
sacrebleu                   2.3.1
safetensors                 0.3.1
tensorboard                 2.14.1
tokenizers                  0.15.1
torch                       2.0.1
transformers                4.36.0
triton                      2.0.0
```

- OS: Red Hat Enterprise Linux 8.8
- Hardware (GPU, or instance type): A100 80GB

## Expected behavior
Successfully runs without any error

## Additional context
Hi, I am trying to train Mosaic BERT model from scratch following the example [here](https://github.com/mosaicml/examples/blob/main/examples/benchmarks/bert/yamls/test/main.yaml). When I run the job on a single node, I don't encounter any error. However, when I try to run on multiple GPUs I get the following error

```
Traceback (most recent call last):                                                                                                                                        
  File "/path_to_user_folder/MosaicML-BERT/bert/main.py", line 316, in <module>                                                                                   
    main(cfg)                                                                                                                                                             
  File "/path_to_user_folder/MosaicML-BERT/bert/main.py", line 224, in main                                                                                       
    train_loader = build_dataloader(                                                                                                                                      
  File "/path_to_user_folder/MosaicML-BERT/bert/main.py", line 181, in build_dataloader                                                                           
    return text_data_module.build_text_dataloader(cfg, tokenizer,                                                                                                         
  File "/path_to_user_folder/MosaicML-BERT/bert/src/text_data.py", line 272, in build_text_dataloader                                                             
    dataset = StreamingTextDataset(                                                                                                                                       
  File "/path_to_user_folder/MosaicML-BERT/bert/src/text_data.py", line 134, in __init__                                                                          
    super().__init__(                                                                                                                                                     
  File "/path_to_user_env/.cache/py39/lib/python3.9/site-packages/streaming/base/dataset.py", line 513, in __init__                                               
    self._shm_prefix_int, self._locals_shm = get_shm_prefix(streams_local, streams_remote,                                                                                
  File "/path_to_user_env/.cache/py39/lib/python3.9/site-packages/streaming/base/shared/prefix.py", line 189, in get_shm_prefix                                   
    prefix_int = _check_and_find_retrying(streams_local, streams_remote, retry)                                                                                           
  File "/path_to_user_env/.cache/py39/lib/python3.9/site-packages/streaming/base/shared/prefix.py", line 162, in _check_and_find_retrying                         
    raise errs[-1]                                                                                                                                                        
  File "/path_to_user_env/.cache/py39/lib/python3.9/site-packages/streaming/base/shared/prefix.py", line 158, in _check_and_find_retrying                         
    return _check_and_find(streams_local, streams_remote)                                                                                                                 
  File "/path_to_user_env/.cache/cb_v1/lib/python3.9/site-packages/streaming/base/shared/prefix.py", line 115, in _check_and_find                                  
    their_locals, _ = _unpack_locals(bytes(shm.buf))                                                                                                                      
  File "/path_to_user_env/.cache/py39/lib/python3.9/site-packages/streaming/base/shared/prefix.py", line 75, in _unpack_locals                                    
    return text[:-1], int(text[-1] or 0)                                                                                                                                  
ValueError: invalid literal for int() with base 10: '/path_to_user_folder/MosaicML-BERT/examples/benchmarks/bert/output/train'                                    

```

**PS:** This issue exits only when I use `mosaicml-streaming` library version greater than `0.5.2`. For version `0.5.2`, the code runs without any error.

Thanks

**Comment by karan6181** [comment]
Hi @murthyrudra, Can you try running `import streaming; streaming.base.util.clean_stale_shared_memory()` once from the terminal using python3 or run it as part of your main.py only once and let us know if you still see the issue?

**Comment by karan6181** [comment]
@murthyrudra wondering, if you get a chance to try out my above suggestion? Thanks!

**Comment by karan6181** [comment]
This issue is being closed due to a lack of activity. Should you continue to encounter the problem, please don't hesitate to reopen it.
