### ISSUE TITLE
merge_index will not merge

### ISSUE THREAD

**Issue by stillmatic** [mosaicml/streaming#618]
## Environment

I have reproduced on two separate machines using same streaming version.

- OS: Ubuntu 22.04, native and WSL
- Hardware (GPU, or instance type): n/a
- `mosaicml-streaming==0.7.4`

## To reproduce

```
from streaming.base.util import _merge_index_from_root, merge_index

>_merge_index_from_root(out="s3://path/to/dataset/", keep_local=False)
Either index_file_urls or out are None. Need to specify both `index_file_urls` and `out`. No index merged
> _merge_index_from_root(out="s3://path/to/dataset/", keep_local=False)
Either index_file_urls or out are None. Need to specify both `index_file_urls` and `out`. No index merged
> merge_index("s3://path/to/dataset/", keep_local=False)
Either index_file_urls or out are None. Need to specify both `index_file_urls` and `out`. No index merged

> merge_index(out="s3://path/to/dataset/", keep_local=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.11/site-packages/streaming/base/util.py", line 248, in merge_index
    if isinstance(args[0], list) and len(args) + len(kwargs) in [2, 3, 4]:
                  ~~~~^^^
IndexError: tuple index out of range
```

## Expected behavior
```
merge_index("s3://path/to/remote", keep_local=False)
WARNING:root:A temporary folder /tmp/tmprv0qy_n_ is created to store index files
```

## Additional context

I'm losing my mind a little bit why this happens. In the case where the tempdir is created, it did not actually write to remote. 

I have been able to run these commands in the past. It's really not clear to me why this would not be deterministic.

**Comment by stillmatic** [comment]
there was a typo. could be more clear that there were no index.json files found but meh, user error
